config/routes.rb
Pictures::Application.routes.draw do
  
  root :to=>"site#index"
	
  get "id:id" => "users#index"
  get "id:id/edit_post" => "users#edit_post"
  get "id:id/new_post" => "users#new_post"
  get "users/sign_up" => "users#new"
  get "categories/:cat/:adress"=>"subcategories#show"
  get "categories/:cat" => "categories#show"
  get ":cat/posts/:id" => "posts#show"
  
  post "users/create" => "users#create", :as=>:user_create
  post 'pict/save_tmp_image' => "picts#save_tmp_image"
  
  put 'post/save_tmp' => "posts#save_tmp"
  put "posts/create_pict" => "posts#create_pict"
  
  delete "picts/:id" => "picts#destroy", :as=>:delete_pict
  delete "comments/:id" => "comments#destroy", :as=>:delete_comment
  
  resources :categories do
		resources :posts do
			resources :picts
			resources :comments
		end
	end
	resources :posts do
		resources :picts
		resources :comments
	end
  
  devise_for :users
  ActiveAdmin.routes(self)
	devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :categorie, class_name: "Categories"
	belongs_to :subcategory
	belongs_to :users
	
	has_many :picts, :dependent => :destroy , :foreign_key=>:post_id
	has_many :comments, :dependent => :destroy , :foreign_key=>:post_id
  
  attr_accessible :text, :adress, :categorie_id, :data, :description, :main_text, :title, :user_id,
                  :subcategory_id, :view, :genre, :series, :technique, :size, :size_h, :size_w, :time_create, :price, :price_type, :pict
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find_by_id(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    @post[:user_id] = current_user.id
    #@post[:categorie_id] = params[:category_id]
    file_name = params[:post][:pict] 
    file = File.join("#{Rails.root}/public/images/poster/big/", file_name)
    tmp_file_path = File.join("#{Rails.root}/public/file_tmp", file_name)
    
    image = MiniMagick::Image.open(tmp_file_path)
    loc = resize_loc(image, params)
    loc = {}
    unless loc.blank?
      FileUtils.cp(tmp_file_path, file)
      File.chmod 0666, file
      image.crop "#{loc[:w]}x#{loc[:h]}+#{loc[:x1]}+#{loc[:y1]}"
      image.resize "200x250"
      image.write "#{Rails.root}/public/images/poster/small/#{file_name}"
    
      File.delete(tmp_file_path) unless File.file?(tmp_file_path)
      if @post.save
        redirect_to @post
      else
        render :text=>"ok"
      end
    else
      render "/users/new_post"
    end
  end
  
  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(params[:post])
      redirect_to @post
    else
      render "show"
    end
  end
  
  def create_pict
    file_name = params[:post][:data]
    @post = Post.find(params[:id])
    unless file_name.blank?
      prev_file_name = @post.pict.to_s
      prev_file_name_big = "public/images/poster/big/#{@post.pict}"
      prev_file_name_small = "public/images/poster/small/#{@post.pict}"
      file_path = File.join(Rails.root.to_s,"/public/file_tmp", file_name)
      image = MiniMagick::Image.open(file_path)
      image.write "public/images/poster/big/#{file_name}"
      loc = resize_loc(image, params)
      unless loc.blank?
        image.crop "#{loc[:w]}x#{loc[:h]}+#{loc[:x1]}+#{loc[:y1]}"
        image.resize "200x250"
        image.write "public/images/poster/small/#{file_name}"
        if File.file?("public/images/poster/big/#{file_name}") && File.file?("public/images/poster/small/#{file_name}") && @post.update_attribute(:pict, file_name)
          File.delete(prev_file_name_big) if !prev_file_name.blank? && File.file?(prev_file_name_big)
          File.delete(prev_file_name_small) if !prev_file_name.blank? && File.file?(prev_file_name_small)
          File.delete(file_path)
          redirect_to @post
        else
          File.delete("public/images/poster/small/#{file_name}") if File.file?("public/images/poster/small/#{file_name}")
          File.delete("public/images/poster/big/#{file_name}") if File.file?("public/images/poster/big/#{file_name}")
          render :text=>"no-save"
        end
      else
        redirect_to @post
      end
    else
      redirect_to @post
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    categorie = @post.categorie
    if @post.destroy
      if categorie.blank?
        wad
        redirect_to root_path
      else
        redirect_to root_path
      end
    end
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_tag("/pict/save_tmp_image",  :enctype=>"multipart/form-data", :target=>"upload_frame", :id=>"upload_form", :style=>"display:none;") do
  = file_field_tag :data, :id=>"post_pict_data"
  = submit_tag

= form_for(@post)  do |f|
  - if @post.errors.any?
    %div#errorExplanation
      %h2
        = pluralize(@post.errors.count, "error")
        prohibited this post from being saved:
      %ul
        -@post.errors.full_messages.each do |msg|
          %li= msg
  
  %div{:style=>"float:left; margin-left:30px; width:200px; height:250px;" }
    %div#post_pict_button{:style=>"width:200px; height:250px; position:absolute; opacity:0;"}
    %div.current_image{:style=>"width:200px; height:250px; background-color:grey;"}
    %div{:style=>"display:none;"}
      =f.text_field :pict, :class=>"pict_name"
      =text_field_tag "x1", id:"x1"
      =text_field_tag "y1", id:"y1"
      =text_field_tag "h", id:"h"
      =text_field_tag "w", id:"w"
      =text_field_tag "o_w", id:"o_w"
      =text_field_tag "o_h", id:"o_h"
      
  .form-input
    = f.label :categorie_id
    %br
    = f.collection_select :categorie_id, Categories.all, :id, :title
    = f.select :subcategory_id, Subcategory.all.collect{|c| [c.title, c.id, {:cat=>c.categories.id}]}
  .form-input
    = f.label :title
    %br
    = f.text_field :title
  

  .form-input
    =f.label :view
    =f.text_field :view
  
  .form-input
    =f.label  :genre
    =f.text_field :genre
    
  .form-input
    =f.label :series
    =f.text_field :series
    
  .form-input
    =f.label :technique
    =f.text_field :technique
  
  .form-input
    =f.label :size
    =f.text_field :size_w, :style=>"width:70px;"
    x
    =f.text_field :size_h, :style=>"width:70px;"
  
  .form-input
    =f.label :time_create
    =f.text_field :time_create
    
  .form-input
    =f.label :price
    =f.text_field :price
    
  .form-input
    =f.label :price_type
    =f.select :price_type, [['p.','1'], ['грн.','2']]
   

  .form-input
    = f.label :text
    = f.text_area :text  
  
  .form-input
    = f.submit

app/views/posts/_form_crop.html.haml
= form_for @post, :url=>{:controller=>:posts, :action=>:create_pict} do |f|
  %div
    %div.current_image
  %p{style:"display:none"}
    = f.label :data
    %br
    = f.text_field :data, :class=>"pict_name"
    
  %div{style:"display:none"}
    =text_field_tag "x1", id:"x1"
    =text_field_tag "y1", id:"y1"
    =text_field_tag "h", id:"h"
    =text_field_tag "w", id:"w"
    =text_field_tag "o_w", id:"o_w"
    =text_field_tag "o_h", id:"o_h"
    =text_field_tag "id", @post.id
  %p
    = f.submit

app/views/posts/_form_image.html.haml
= form_for(@post,:url=>"/post/save_tmp" ,  :enctype=>"multipart/form-data", :html=>{:target=>"upload_frame", :id=>"upload_form"}) do |f|
  %p
    = f.label :data
    %br
    = f.file_field :data 
  %p
    = f.submit

app/views/posts/_new.js.erb
$('#add_posts').html("= escape_javascript( render :new)");

app/views/posts/_one.html.haml
%div.view-post
  %div.view-post-link
    =link_to post.title, {:id=>post.id, :controller=>:posts, :action=>:show, :cat=>post_cat_adress(post)}
  %div.view-post-image
    -unless post.pict.blank?
      =link_to image_tag("/images/poster/small/"+post.pict.to_s, :width=>'200', :height=>'250'), {:id=>post.id, :controller=>:posts, :action=>:show, :cat=>post_cat_adress(post)}
    -else
      %div{:style=>"width:200px; height:150px;"}
        Не существует  
  %div.view-post-comment
    Кол зап. 
    = post.comments.count 
  
  
  %p
    -#if !current_user.blank? && (current_user.admin? || post.user_id == current_user.id ) 
      =link_to "Удалить", post_path(post), :method=>:delete

app/views/posts/_show_carusel.html.haml
%div#show-carusel  
  %div#show-carusel-all
    - i = 0
    -post.picts.each do |pict|
      - next if pict.adress.blank?
      - if !current_user.blank? && (current_user.admin? || current_user.id == pict.post.user_id)
        =#link_to "Удалить", delete_pict_path(pict), method: :delete
      =image_tag "/images/picture/small/#{pict.adress}", :width=>'200', :class=>"image-show", :id=>"image_min_#{i}", :onclick=>"set_current(this)"
      - i+=1

%div#show_big.center-align
  %img#file_tmp{:style=>"display:none"}
  %div#close_link 
  %div#prev_link Влево
  %div#next_link Вправо
  %img#set_image
  

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.haml
%h1 Listing Posts
%table
  %tr
    %th Title
    %th Text
    %th
    %th
    %th
 
  - @posts.each do |post|
    %tr
      %td
        = post.title
      %td
        = post.text
      %td
        = link_to 'Show', :action => :show, :id => post.id
      %td
        = link_to 'Edit', :action => :edit, :id => post.id
      %td
        = link_to 'Destroy', { :action => :destroy, :id => post.id },:remote => true, :confirm => 'Are you sure?', :method => :delete

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
-if user_signed_in? && (current_user.admin? || current_user.id == @post.user_id) 
  %div#edit_post_click 
    %div#edit_post_menu
      %div#add_pict_link
        %a{:href=>"#"} Добавить изображение
      %div= link_to "Обновить", edit_post_path(@post)
      %div= link_to "Удалить запись", post_path(@post), :method=>:delete   
    %span.border-radius#add_pict_click_link P
    %span.border-radius#edit_cat_click_link C
    %span.border-radius#show_edit_post_menu <<
    
  %div#add_pict_image.center-align.border-radius{:style=>"display:none;"}
    = render "picts/form_pict"

  %div#add-pict-crop.center-align.border-radius
    = render "posts/form_crop"
  %div#add_pict_crop_image.center-align.border-radius{:style=>"display:none;"} 
    = render "picts/form_crop"
  
  %div#edit_cat.center-align.border-radius.hide
    = render "categories/change"

%div#post
  %div#post_title= @post.title 

  %div#post_image= image_tag "/images/poster/big/#{@post.pict}", :width=>"600px"
  
  %table
    %tr
      %th{:style=>"width:200px;"}
      %th{:style=>"width:200px;"}
    %tr.blue
      %td#post_view_label.label Вид искуства:
      %td#post_view.value=@post.view 
    %tr
      %td#post_genre_label.label Жанр:
      %td#post_ganre.value= @post.genre
    %tr
      %td.label Техника
      %td.value= @post.technique
    %tr
      %td.label Размер
      %td.value= "#{@post.size_h}см x #{@post.size_w}см"
    %tr
  
= render "show_carusel", :post=>@post

%div{:style=>"margin:30px;"}
  %h2{:style=>"text-align:center; text-decoration:underline;"} Коментарии
  %div#add_coment
    - @post.comments.each do |comment|
      %div= comment.message
      %div{:style=>"text-align:right;"}= "прокоментировал #{comment.user_name} в #{comment.created_at.strftime('%Y.%d.%m:%H.%M')}"
      -if !current_user.blank? && comment.user_id == current_user.id
        = link_to "Удалить", delete_comment_path(comment), :method=>:delete
%h2 Добавить комментарий:
= render "comments/form"  